name: Build/release

on: push

# env:
#   GH_TOKEN: ${{ secrets.JOSE_ADE }}

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Log1
        run: echo "${{github.ref}}"
      - name: Log2
        run: echo "${{startsWith(github.ref, 'refs/tags/v')}}"

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "v2.1.5"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        run: CSC_LINK="${{ secrets.MAC_CERT }}" CSC_KEY_PASSWORD="${{ secrets.MAC_CERT_PASSWORD }}" WIN_CSC_LINK="${{ secrets.WINDOWS_CERT }}" WIN_CSC_KEY_PASSWORD="jose" npm run release
