name: Build/release

on: push

env:
  GH_TOKEN: ${{ secrets.JOSE_ADE }}

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        
      - name: Build/release Electron app
        run: npm run release
